"""Initial migration v2

Revision ID: 7c56532ac126
Revises: 
Create Date: 2026-01-22 00:32:47.339453+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  


# revision identifiers, used by Alembic.
revision: str = '7c56532ac126'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_aqi_threshold', sa.Integer(), nullable=False, comment='Minimum AQI value to trigger this rule'),
    sa.Column('condition_tag', sa.String(length=100), nullable=True, comment='Health condition to match (null = all users)'),
    sa.Column('message_template', sa.Text(), nullable=False, comment='Message template with {placeholders}'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='Action type: info, warning, alert, emergency'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advice_rules'))
    )
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger_metric', sa.String(length=50), nullable=False, comment='Metric to monitor: outdoor_aqi, indoor_aqi, pm25'),
    sa.Column('threshold_value', sa.Integer(), nullable=False, comment='Threshold to trigger action, e.g., 150'),
    sa.Column('action_payload', sa.JSON(), nullable=False, comment='Action to execute: {"power": "on", "mode": "turbo"}'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rules'))
    )
    op.create_index(op.f('ix_automation_rules_user_id'), 'automation_rules', ['user_id'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.Enum('BURNING', 'DUST', 'SMOKE', 'CHEMICAL', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='Location as PostGIS Point geometry'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='URL to uploaded incident image'),
    sa.Column('description', sa.Text(), nullable=True, comment='User description of the incident'),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False, comment='Credibility score from 0.0 to 1.0'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_reports'))
    )
    op.create_index('idx_community_reports_geom', 'community_reports', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_community_reports_user_id'), 'community_reports', ['user_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String(length=100)), nullable=True, comment='Health conditions: asthma, sinus, heart_disease, etc.'),
    sa.Column('sensitivity_level', sa.Integer(), nullable=False, comment='Sensitivity level from 1 (low) to 5 (high)'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_health_profiles'))
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('IQAIR', 'PAMAIR', name='stationsource'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations'))
    )
    op.create_table('user_devices',
    sa.Column('device_id', sa.String(length=100), nullable=False, comment='Unique device identifier, e.g., xiaomi.air.p3'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Device provider: xiaomi, samsung, philips, dyson'),
    sa.Column('access_token', sa.String(length=500), nullable=True, comment='OAuth token for device API'),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('current_filter_life', sa.Integer(), nullable=True, comment='Filter life percentage (0-100)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_user_devices'))
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('air_quality_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_air_quality_logs_station_id_stations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_air_quality_logs'))
    )
    op.create_index('ix_air_quality_logs_station_recorded', 'air_quality_logs', ['station_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_air_quality_logs_station_recorded', table_name='air_quality_logs')
    op.drop_table('air_quality_logs')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_table('stations')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_community_reports_user_id'), table_name='community_reports')
    op.drop_index('idx_community_reports_geom', table_name='community_reports', postgresql_using='gist')
    op.drop_table('community_reports')
    op.drop_index(op.f('ix_automation_rules_user_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_table('advice_rules')
    # ### end Alembic commands ###
